api_platform:
    metadata_backward_compatibility_layer: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json', 'application/json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
