version: '2'

services:
    myapp:
        image: 'bitnami/symfony:5.4'
        ports:
            - '${SYMFONY_APP_PORT-8000}:8000'
        volumes:
            - '.:/app'
        environment:
            SYMFONY_DATABASE_HOST: '${SYMFONY_DATABASE_HOST}'
            SYMFONY_DATABASE_PORT_NUMBER: 3306
            SYMFONY_DATABASE_USER: '${SYMFONY_DATABASE_USER}'
            SYMFONY_DATABASE_PASSWORD: '${SYMFONY_DATABASE_PASSWORD}'
            SYMFONY_DATABASE_NAME: '${SYMFONY_DATABASE_NAME}'
            SYMFONY_PROJECT_SKELETON: 'symfony/skeleton'
        depends_on:
            - mariadb
    mariadb:
        image: 'bitnami/mariadb:10.11'
        environment:
            ALLOW_EMPTY_PASSWORD: 'yes'
            MARIADB_USER: '${SYMFONY_DATABASE_USER}'
            MARIADB_PASSWORD: '${SYMFONY_DATABASE_PASSWORD}'
            MARIADB_DATABASE: '${SYMFONY_DATABASE_NAME}'
        ports:
            - '${SYMFONY_DATABASE_PORT:-3306}:3306'