#index:
#    path: /
#    controller: App\Controller\DefaultController::index

admin:
    path: /admin
    controller: App\Controller\Admin\DefaultDashboardController::index

api_login:
    path:       /api_login
    methods:    POST