#index:
#    path: /
#    controller: App\Controller\DefaultController::index

admin:
    path: /admin
    controller: App\Controller\Admin\DefaultController::index

login:
    path:       /login
    controller: App\Controller\SecurityController::login
    methods: POST
